### ISSUE TITLE
Initial Phoneme Task

### ISSUE THREAD

**Issue by Carpeje** [donalcarpenter/phonemeapp#10]
1. Number 4 - new audio needed and new image for book
2. Number 6 - new audio needed and new image for tie
3. Number 7 & 8 - new audio needed for 'c'
4. Number 10 - new audio needed and new image for boat
5. Final audio comment to complete the task needed

**Comment by donalcarpenter** [comment]
new book, boat & tie images added
all new audio files incorporated
added final comment too
